spring.application.name=proyectoFutbol

# ========== BASE DE DATOS H2 ==========
spring.datasource.url=jdbc:h2:mem:footballdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ========== JPA / HIBERNATE ==========
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========== CONSOLA H2 (para ver la BD en navegador) ==========
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
